import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { map, first } from 'rxjs/operators';
import { AngularFireAuth } from "@angular/fire/auth";
import { AngularFirestore } from '@angular/fire/firestore';
import { ToastrManager } from 'ng6-toastr-notifications';


@Component({
  selector: 'app-registro',
  templateUrl: './registro.component.html',
  styleUrls: ['./registro.component.css']
})
export class RegistroComponent implements OnInit {

  usuario:any={nombres:'',apellidos:'',colegio:'',colegioOtro:'',turno:'',curso:'',telefono:''};
  colegios = [
    'ALEMÁN DEL SUD - CERCADO',
    'AMERICANO DE TARIJA - CERCADO',
    'AVELINA RAÑA 2 - CERCADO',    
    'ANICETO ARCE-CERCADO', //Gestión 2022
    'BANCARIO - CERCADO',
    'BOLIVIA 2 - CERCADO',
    'CANDY COLODRO DE REYES - CERCADO',
    'CARMEN MEALLA - CERCADO',
    'CASTELFORT CASTELLANOS TM - CERCADO',
    'CASTELFORT CASTELLANOS TT - CERCADO',
    'CEA BELGRANO - CERCADO',
    'CEA SAN JERÓNIMO ADULTOS - CERCADO',
    'CEA SAN ROQUE - CERCADO',
    'CEA TARIJA ADULTOS - CERCADO',
    'DR. ALBERTO BALDIVIEZO - CERCADO',
    'EL PORTILLO-CERCADO',
    'ESTEBAN MIGLIACCI TM - CERCADO',
    'ESTEBAN MIGLIACCI TT - CERCADO',
    'EULOGIO RUIZ - CERCADO',
    'EVANGELICA BAUTISTA TARIJA (UBEET) - CERCADO',
    'HERMANN GMEINER - CERCADO',
    'HNA. TERESA DE CALCUTA - CERCADO',
    'HNO. FELIPE PALAZÓN- CERCADO',
    'HUMBERTO PORTOCARRERO B. II - CERCADO',
    'JESÚS DE NAZARETH - CERCADO', //MODIFICADO
    'JORGE ARAOZ CAMPERO - CERCADO',
    'JOSÉ MANUEL ÁVILA 1 - CERCADO',
    'JOSÉ MANUEL ÁVILA 2 - CERCADO',
    'JOSÉ MANUEL BELGRANO - CERCADO',
    'JOSÉ MARÍA VELAZ 2 - CERCADO',
    'JOSÉ NAVAL MONZON CARDOZO - CERCADO',
    'JUAN PABLO II - CERCADO',
    'JUAN XXIII 2 - CERCADO',
    'JUANA AZURDUY DE PADILLA 1 - CERCADO',
    'JULIO CALVO - CERCADO',
    'LA PAZ - CERCADO',
    'LA SALLE PRIVADO - CERCADO',
    'LA SALLE CONVENIO - CERCADO',
    'LIDIA DE CAMPOS - CERCADO',
    'LINDAURA A. DE CAMPERO TM - CERCADO',
    'LINDAURA A. DE CAMPERO TT - CERCADO',
    'LOURDES - CERCADO',
    'MARÍA LAURA JUSTINIANO II - CERCADO',
    'NACIONAL EUSTAQUIO MÉNDEZ - CERCADO',
    'NACIONAL EUSTAQUIO MÉNDEZ NOCTURNO - CERCADO',
    'NACIONAL SAN LUIS - CERCADO',
    'NACIONAL SAN LUIS NOCTURNO - CERCADO',
    'NARCISO CAMPERO II - CERCADO',
    'NAZARIA IGNACIA MARCH - CERCADO',
    'OCTAVIO CAMPERO ECHAZÚ - CERCADO',
    'PAMPA GALANA - CERCADO',
    'SAN BERNARDO DE TARIJA - CERCADO',
    'SAN JERÓNIMO - CERCADO',
    'SAN JORGE I - CERCADO',
    'SAN JORGE II - CERCADO',
    'SAN LUIS - CERCADO',
    'SAN ROQUE - CERCADO',
    'SANTA ANA 3 - CERCADO',
    'TARIJA - CERCADO',
    'TARIJA 1 - CERCADO',
    'TARIJA 3 - CERCADO',
    'TERCERA ORDEN FRANCISCANA I - CERCADO',
    '15 DE ABRIL - CERCADO',
    'GUERRAHUAYCO - CERCADO',
    'LUIS DE FUENTES Y VARGAS - CERCADO',
    'PEDRO RIVERA - CERCADO', //MODIFICADO
    'SAN MATEO - CERCADO',
    'TOLOMOSA GRANDE - CERCADO',
    'TURUMAYO - CERCADO', //GESTION 2022
    'YESERA NORTE - CERCADO',
    'ANICETO ARCE - AVILÉS',
    'CEA CONCEPCIÓN - AVILÉS',
    'CEA  NUESTRA SEÑORA DEL ROSARIO ADULTOS - AVILÉS', //GESTION 2022
    'DELFIN PINO ECHAZÚ - AVILÉS',
    'LIBERTAD - AVILÉS',
    'PROF. ROSARIO JARAMILLO - AVILÉS',
    'SANTA CECILIA - AVILÉS',
    'SANTA ANA LA NUEVA - CERCADO', //MODIFICADO
    'CETHA SAN JOSE DE CHARAJA - AVILÉS',
    '15 DE OCTUBRE - AVILÉS',
    'ÁNGEL CALABI PAZZOLINI 2 - MÉNDEZ',
    'CARACHIMAYO - MÉNDEZ',
    'CENTRO SANTA ISABEL - MÉNDEZ',
    'JULIO SUCRE - MÉNDEZ',
    'LUIS CARRASCO SALINAS - MÉNDEZ',
    'PROF. OSVALDO GÁLVEZ - MÉNDEZ',
    'RANCHO NORTE - MÉNDEZ',
    'SIMÓN BOLÍVAR - MÉNDEZ', //MODIFICADO
    'TOMATAS GRANDE - MÉNDEZ',
    '15 DE ABRIL - MÉNDEZ', //GESTION 2022
    'JARCAS - MÉNDEZ', //GESTION 2022
    'ADVENTISTA ESPAADY - YACUIBA - GRAN CHACO',
    'CEA YACUIBA ADULTOS - YACUIBA - GRAN CHACO',
    'CORONEL MIGUEL ESTENSORO - YACUIBA - GRAN CHACO',
    'CEA LIBERTADOR SIMÓN BOLÍVAR 3 - YACUIBA - GRAN CHACO',
    'CLUB DE LEONES II - YACUIBA - GRAN CHACO',
    'GRAL. MANUEL BELGRANO - YACUIBA - GRAN CHACO',
    'GERMAN BUSCH - YACUIBA - GRAN CHACO',
    'NÉSTOR PAZ GALARZA-YACUIBA- GRAN CHACO', //GESTION 2022
    'HÉROES DEL CHACO - YACUIBA - GRAN CHACO',
    'LICEO GRAN CHACO - YACUIBA - GRAN CHACO',
    'LIBERTADOR SIMÓN BOLÍVAR 4 - YACUIBA - GRAN CHACO',
    'MARISCAL SUCRE - YACUIBA - GRAN CHACO',
    'PDTE. GERMÁN BUSCH NOCTURNO - YACUIBA - GRAN CHACO',
    'SAGRADO CORAZON DE JESÚS PARTICULAR - YACUIBA - GRAN CHACO',
    'SAGRADO CORAZON DE JESÚS TT - YACUIBA - GRAN CHACO',
    'PARTICULAR MIXTO BOLIVIA - YACUIBA - GRAN CHACO',
    'REVERENDO OLIVERIO PELLICHELLI - YACUIBA - GRAN CHACO',
    'YACUIBA SECUNDARIO - YACUIBA - GRAN CHACO',
    'ASAMBLEA DE DIOS - VILLAMONTES - GRAN CHACO',
    'ADELA HOYOS MORALES - VILLAMONTES - GRAN CHACO',
    'BOQUERÓN - VILLAMONTES - GRAN CHACO',
    'CRISTO REY - VILLAMONTES - GRAN CHACO',
    'CEA WENHAYEK - VILLAMONTES - GRAN CHACO',
    'CEA VILLAMONTES - VILLAMONTES - GRAN CHACO',
    'DEFENSORES DEL CHACO - VILLAMONTES - GRAN CHACO',
    'ELIODOLID TEJERINA GUTIERREZ - VILLAMONTES - GRAN CHACO',
    'FAUSTINO SUAREZ ARNES - VILLAMONTES - GRAN CHACO',
    'ISMAEL MONTES DIURNO - VILLAMONTES - GRAN CHACO',
    'SAN ANTONIO - VILLAMONTES - GRAN CHACO',
    'JULIO CREVAUX - VILLAMONTES - GRAN CHACO',
    'REPUBLICA DE BOLIVIA - VILLAMONTES - GRAN CHACO',
    'SANTA CLARA - VILLAMONTES - GRAN CHACO',
    'ISMAEL MONTES NOCTURNO - VILLAMONTES - GRAN CHACO',
    'MANUEL CUELLAR - CARAPARI - GRAN CHACO',
    "FRANZ TAMAYO FE Y ALEGRÍA - O'CONNOR",
    "GRL. FRANCISCO BURDET O'CONNOR II - O'CONNOR",
    "NUESTRA SEÑORA DEL ROSARIO - O'CONNOR",
    'AULIO ARAOZ - BERMEJO - ARCE',
    'ANTONIO JOSÉ DE SUCRE - BERMEJO - ARCE',
    'BOLIVIA DIURNO - BERMEJO - ARCE',
    'BOLIVIA NOCTURNO - BERMEJO - ARCE',
    '8 DE SEPTIEMBRE - BERMEJO - ARCE',
    'JUANA AZURDUY DE PADILLA II - BERMEJO - ARCE', //GESTION 2022
    'CEA BERMEJO - BERMEJO - ARCE',
    'EDUARDO ABAROA - BERMEJO - ARCE',
    'GUIDO VILLAGÓMEZ SECUNDARIO - BERMEJO - ARCE',
    'MARISCAL ANDRÉS DE SANTA CRUZ - BERMEJO - ARCE',
    'NAL. MIXTO 25 DE MAYO - BERMEJO - ARCE',
    'OCTAVIO CAMPERO ECHAZÚ - FE Y ALEGRÍA - BERMEJO - ARCE',
    'LA ESPERANZA - BERMEJO - ARCE',
    'CAMPO GRANDE - BERMEJO - ARCE',
    'JOSÉ MARÍA LINARES - BERMEJO - ARCE',
    'CAÑAS - ARCE', //MODIFICADO
    'CAMACHO - ARCE', //MODIFICADO
    'CEA- ESTELA COCA - ARCE', //MODIFICADO
    'PROF. JOSÉ QUIROGA LAIME - ARCE', //MODIFICADO
    'RENÉ BARRIENTOS ORTUÑO - ARCE', //MODIFICADO
    //agregado de anexo 1 enviado por licen cecilia
    'NACIONAL MIXTO 3 DE ABRIL-CAMARGO-CHUQUISACA',
    "BOLIVIA SECUNDARIO-CAMARGO-CHUQUISACA",
    "NACIONAL MIXTO CHOROLQUE-TUPIZA-POTOSÍ",
    "SUIPACHA-TUPIZA-POTOSÍ",
    "JAIME MENDOZA-TUPIZA-POTOSÍ",
    "SANTA ANA-TUPIZA-POTOSÍ",
    "ANDRÉS DE SANTA CRUZ-TUPIZA-POTOSÍ",
    "NACIONAL 9 DE ABRIL “A”- VILLAZÓN-POTOSÍ",
    "MARCELO QUIROGA SANTA CRUZ “B”- VILLAZÓN-POTOSÍ",
    "FRANZ TAMAYO DE LA FRONTERA-VILLAZÓN-POTOSÍ",
    "MAX FERNÁNDEZ ROJAS-VILLAZÓN-POTOSÍ",
    '6 DE JUNIO "B"- VILLAZÓN - POTOSÍ',
    "1º DE MAYO-VILLAZÓN-POTOSÍ",
    "23 DE MARZO-VILLA ABECIA-CHUQUISACA",
    "SAN MIGUEL - EL PUENTE - MÉNDEZ", //MODIFICADO
    "TARIJA - ISCAYACHI - MÉNDEZ", //MODIFICADO
    "YUNCHARA - AVILÉS", //MODIFICADO
    "LINDAURA ANZUATEGUI DE CAMPERO - TOJO - AVILÉS", //MODIFICADO
    "TEOFILO ALARCON - YUNCHARA - AVILÉS", //MODIFICADO
    "CETHA EL PUENTE - ISCAYACHI - MÉNDEZ", //MODIFICADO
    "EL MOLINO - MÉNDEZ", //MODIFICADO
    "PAICHO CENTRO MÉNDEZ", //MODIFICADO
    'ÓSCAR ALFARO - YUNCHARÁ - AVILÉS', //GESTION 2022
    'PUEBLO NUEVO - EL PUENTE - MÉNDEZ', //GESTION 2022
    'T. CNL GUALBERTO BALDIVIEZO - LA CUEVA- O´CONNOR', //GESTION 2022
  ];

  constructor(public firestore: AngularFirestore,
    private router:Router,
    private afAuth:AngularFireAuth,
    public toastr: ToastrManager
  ) { 
  }

  ngOnInit(): void {
  }
  registro(){
    this.afAuth.user.subscribe(u=>{
      this.guadarUsuario(u.uid).then(()=>{
        this.router.navigate(['/principal']); 
      })
    })
    this.colegios.sort();
  }
  guadarUsuario(key){
    
    if(this.usuario.telefono.includes(".")){
      this.toastr.warningToastr('El numero de telefono no debe contener .', 'Datos Incompletos!');
    }
    else if(this.usuario.telefono.length == 8 && isNaN(this.usuario.telefono ) == false ){
      this.usuario.colegio = this.usuario.colegio.toUpperCase()
      return this.firestore.doc('usuarios/'+key).set(this.usuario);
    }else{
      this.toastr.warningToastr('El numero de telefono debe contener 8 digitos', 'Datos Incompletos!');
    }
  }
}
